// ============================================================
// PDF Generator - Client-side PDF generation using jsPDF
// ============================================================

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { PriceListData, UserSettings } from '@/types';

/**
 * Generate a professional PDF of the price list.
 * Returns a Blob that can be downloaded or shared.
 */
export function generatePDF(
  priceList: PriceListData,
  settings: UserSettings
): Blob {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Colors
  const primaryRed: [number, number, number] = [220, 38, 38];
  const darkText: [number, number, number] = [28, 25, 23];
  const grayText: [number, number, number] = [120, 113, 108];
  const lightBg: [number, number, number] = [250, 250, 249];

  // ── Header background ──
  doc.setFillColor(...primaryRed);
  doc.rect(0, 0, pageWidth, 45, 'F');

  // ── Shop name ──
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(priceList.shopName || 'Chicken Shop', pageWidth / 2, 22, {
    align: 'center',
  });

  // ── Subtitle ──
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Daily Price List', pageWidth / 2, 32, { align: 'center' });

  // ── Date ──
  doc.setFontSize(11);
  const formattedDate = formatDate(priceList.date);
  doc.text(formattedDate, pageWidth / 2, 40, { align: 'center' });

  // ── Price table ──
  const tableData = priceList.items
    .filter((item) => item.price > 0)
    .sort((a, b) => a.orderIndex - b.orderIndex)
    .map((item, index) => [
      (index + 1).toString(),
      item.itemName,
      `${settings.currency}${item.price}`,
      item.unit || settings.defaultUnit,
      item.note || '',
    ]);

  autoTable(doc, {
    startY: 55,
    margin: { left: margin, right: margin },
    head: [['#', 'Item', 'Price', 'Unit', 'Note']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: primaryRed,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 12,
      halign: 'center',
      cellPadding: 5,
    },
    bodyStyles: {
      fontSize: 11,
      cellPadding: 5,
      textColor: darkText,
    },
    alternateRowStyles: {
      fillColor: lightBg,
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 12 },
      1: { cellWidth: contentWidth * 0.35, fontStyle: 'bold' },
      2: {
        halign: 'right',
        cellWidth: contentWidth * 0.18,
        fontStyle: 'bold',
        textColor: primaryRed,
      },
      3: { halign: 'center', cellWidth: contentWidth * 0.18 },
      4: { cellWidth: contentWidth * 0.2, fontSize: 9, textColor: grayText },
    },
    didDrawPage: () => {
      // Footer on every page
      const pageHeight = doc.internal.pageSize.getHeight();

      if (settings.showFooter && settings.footerText) {
        doc.setFontSize(9);
        doc.setTextColor(...grayText);
        doc.setFont('helvetica', 'italic');
        doc.text(settings.footerText, pageWidth / 2, pageHeight - 15, {
          align: 'center',
          maxWidth: contentWidth,
        });
      }

      // Page number
      doc.setFontSize(8);
      doc.setTextColor(180, 180, 180);
      doc.text(
        `Generated by Chicken Price Manager`,
        pageWidth / 2,
        pageHeight - 8,
        { align: 'center' }
      );
    },
  });

  return doc.output('blob');
}

/**
 * Format a date string (YYYY-MM-DD) to a human-readable format.
 */
function formatDate(dateStr: string): string {
  try {
    const date = new Date(dateStr + 'T00:00:00');
    return date.toLocaleDateString('en-IN', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  } catch {
    return dateStr;
  }
}
